name: Build and Push Docker Images

on:
  push:
    branches: [notmain]  # Ваша ветка

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Обязательные настройки сборки
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Сборка и пуш сервиса Регистратура
      - name: Build & Push Registry Service
        uses: docker/build-push-action@v4
        with:
          context: lab6_devops/app_registry
          file: lab6_devops/app_registry/Dockerfile  # Явное указание Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_registry:latest

      # Сборка и пуш сервиса Расписание
      - name: Build & Push Schedule Service
        uses: docker/build-push-action@v4
        with:
          context: lab6_devops/app_schedule
          file: lab6_devops/app_schedule/Dockerfile  # Явное указание Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_schedule:latest

      # Сборка и пуш миграций БД (если нужно)
      - name: Build & Push DB Migrations
        uses: docker/build-push-action@v4
        with:
          context: lab6_devops/db_migrations
          file: lab6_devops/db_migrations/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/db_migrations:latest