name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches: [notmain]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Runner OS: $(uname -a)"
          ls -la